pipeline {
    agent any
    
    stages {
        stage('Verify Files') {
            steps {
                echo 'Checking workspace...'
                sh 'pwd'
                sh 'ls -la'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t hello-captain /workspace'
            }
        }
        
        stage('Run Docker Container') {
            steps {
                echo 'Running Docker container...'
                sh 'docker run --rm hello-captain'
            }
        }
        
        stage('Cleanup') {
            steps {
                echo 'Cleaning up...'
                sh 'docker rmi hello-captain || true'
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline completed successfully!'
            echo 'You should see: Hello, Tiffany!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}