---
# Advanced example showing variable usage
# This is an OPTIONAL alternative approach

- name: Configure Web Server (Advanced)
  hosts: webservers
  become: yes
  
  vars:
    # Application variables
    app_name: "mywebsite"
    web_root: "/var/www/html"
    nginx_port: 80
    
    # Security settings
    fail2ban_bantime: 3600
    fail2ban_maxretry: 5
    
    # Package lists
    base_packages:
      - curl
      - wget
      - vim
      - git
      - htop
      - unzip
      - net-tools
  
  roles:
    - role: base
      tags: ['base', 'always']
    
    - role: ssh
      tags: ['ssh', 'security']
    
    - role: nginx
      tags: ['nginx', 'web']
    
    - role: app
      tags: ['app', 'deploy']
